# Generated by Django 4.2.16 on 2026-04-29 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box_calculator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxcalcitem',
            name='category',
            field=models.CharField(choices=[('books', 'Books'), ('kitchen', 'Kitchen'), ('fragile_kitchen', 'Fragile Kitchen'), ('general', 'General'), ('linens', 'Linens'), ('hanging_clothes', 'Hanging Clothes'), ('folded_clothes', 'Folded Clothes'), ('toys', 'Toys'), ('decor', 'Decor'), ('electronics', 'Electronics'), ('dresser', 'Dresser'), ('nightstand', 'Nightstand'), ('filing_cabinet', 'Filing Cabinet'), ('desk', 'Desk'), ('bed_frame', 'Bed Frame'), ('headboard', 'Headboard'), ('mattress', 'Mattress'), ('sofa', 'Sofa'), ('chair', 'Chair'), ('dining_table', 'Dining Table'), ('entertainment_center', 'Entertainment Center'), ('bookshelf', 'Bookshelf'), ('china_cabinet', 'China Cabinet'), ('appliance_large', 'Appliance Large'), ('artwork_large', 'Artwork Large')], max_length=40),
        ),
    ]
