# Generated by Django 4.2.16 on 2026-05-24 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('box_calculator', '0002_alter_boxcalcitem_category'),
        ('box_calculator', '0003_rename_ppr_to_cps'),
    ]

    operations = [
    ]
