# Generated by Django 4.2.16 on 2025-11-21 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docsAppR', '0002_change_default_los_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomworktypevalue',
            name='value_type',
            field=models.CharField(choices=[('LOS', 'Line Of Sight'), ('TRAVEL', 'Travel Area'), ('NA', 'Not Applicable')], default='NA', max_length=10),
        ),
    ]
