# Generated by Django 5.1.4 on 2025-06-24 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docsAppR', '0002_alter_file_options_file_created_at_alter_file_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('MIT_AUTH', 'MIT General Authorization'), ('MIT_AGREE', 'MIT Customer Agreement'), ('MIT_W9', 'MIT W9 Form'), ('MIT_VERIFY', 'MIT Jobsite Verification'), ('MIT_EQUIP', 'MIT Equipment Pictures'), ('MIT_INVOICE', 'MIT Xactimate Invoice'), ('MIT_OVERVIEW', 'MIT Job Overview Pictures'), ('MIT_DRYLOG', 'MIT Dry Logs Reports'), ('MIT_EMAIL', 'MIT Email Cover Sheet'), ('CPS_AUTH', 'CPS General Authorization'), ('CPS_AGREE', 'CPS Customer Agreement'), ('CPS_W9', 'CPS W9 Form'), ('CPS_VERIFY', 'CPS Jobsite Verification'), ('CPS_BOXCOUNT', 'CPS Box Count Report'), ('CPS_BOXPHOTO', 'CPS Box Count Photo Report'), ('CPS_CUSTPICS', 'CPS Customer Pics'), ('CPS_CUSTLIST', 'CPS Customer List'), ('CPS_INVOICE', 'CPS Xactimate Packout Invoice'), ('CPS_ESX', 'CPS ESX File'), ('CPS_OVERVIEW', 'CPS Job Overview Pictures'), ('CPS_DAY1', 'CPS Day1 Overview Pics'), ('CPS_DAY2', 'CPS Day2 Work In Progress'), ('CPS_DAY3', 'CPS Day3 Storage Pics'), ('CPS_DAY4', 'CPS Day4 Demo/Reset Pics'), ('CPS_EMAIL', 'CPS Email Cover Sheet'), ('PPR_SCHEDULE', 'PPR Schedule of Loss'), ('PPR_PHOTOREP', 'PPR Items Photo Report'), ('PPR_CUSTPICS', 'PPR Customer Pics'), ('PPR_CUSTLIST', 'PPR Customer List'), ('PPR_EMAIL', 'PPR Email Cover Sheet')], max_length=20)),
                ('template_file', models.FileField(upload_to='document_templates/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('MIT_AUTH', 'MIT General Authorization'), ('MIT_AGREE', 'MIT Customer Agreement'), ('MIT_W9', 'MIT W9 Form'), ('MIT_VERIFY', 'MIT Jobsite Verification'), ('MIT_EQUIP', 'MIT Equipment Pictures'), ('MIT_INVOICE', 'MIT Xactimate Invoice'), ('MIT_OVERVIEW', 'MIT Job Overview Pictures'), ('MIT_DRYLOG', 'MIT Dry Logs Reports'), ('MIT_EMAIL', 'MIT Email Cover Sheet'), ('CPS_AUTH', 'CPS General Authorization'), ('CPS_AGREE', 'CPS Customer Agreement'), ('CPS_W9', 'CPS W9 Form'), ('CPS_VERIFY', 'CPS Jobsite Verification'), ('CPS_BOXCOUNT', 'CPS Box Count Report'), ('CPS_BOXPHOTO', 'CPS Box Count Photo Report'), ('CPS_CUSTPICS', 'CPS Customer Pics'), ('CPS_CUSTLIST', 'CPS Customer List'), ('CPS_INVOICE', 'CPS Xactimate Packout Invoice'), ('CPS_ESX', 'CPS ESX File'), ('CPS_OVERVIEW', 'CPS Job Overview Pictures'), ('CPS_DAY1', 'CPS Day1 Overview Pics'), ('CPS_DAY2', 'CPS Day2 Work In Progress'), ('CPS_DAY3', 'CPS Day3 Storage Pics'), ('CPS_DAY4', 'CPS Day4 Demo/Reset Pics'), ('CPS_EMAIL', 'CPS Email Cover Sheet'), ('PPR_SCHEDULE', 'PPR Schedule of Loss'), ('PPR_PHOTOREP', 'PPR Items Photo Report'), ('PPR_CUSTPICS', 'PPR Customer Pics'), ('PPR_CUSTLIST', 'PPR Customer List'), ('PPR_EMAIL', 'PPR Email Cover Sheet')], max_length=20)),
                ('document_category', models.CharField(choices=[('MIT', 'Mitigation'), ('CPS', 'Contents Processing'), ('PPR', 'Property Repair')], max_length=3)),
                ('is_completed', models.BooleanField(default=False)),
                ('required', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='docsAppR.client')),
            ],
            options={
                'ordering': ['document_category', 'document_type'],
            },
        ),
    ]
