# Generated by Django 5.1.4 on 2025-06-24 13:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docsAppR', '0003_documenttemplate_checklistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='completion_percent',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
