# Generated by Django 4.2.16 on 2025-12-08 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docsAppR', '0002_remove_onedrive_sync_status'),
        ('docsAppR', '0003_revert_default_to_na_master_slave'),
    ]

    operations = [
    ]
