# Generated by Django 5.1.4 on 2025-06-29 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docsAppR', '0007_landlord_document_landlord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landlord',
            name='name',
        ),
        migrations.AddField(
            model_name='landlord',
            name='account_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Account Holder Name'),
        ),
        migrations.AddField(
            model_name='landlord',
            name='account_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='landlord',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='landlord',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='landlord',
            name='default_eviction_day',
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='landlord',
            name='default_late_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='landlord',
            name='default_late_fee_start_day',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='landlord',
            name='default_max_occupants',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='landlord',
            name='default_nsf_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='landlord',
            name='default_rent_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='landlord',
            name='default_rent_due_day',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='landlord',
            name='default_security_deposit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='landlord',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Full Legal Name'),
        ),
        migrations.AddField(
            model_name='landlord',
            name='property_address',
            field=models.TextField(blank=True, verbose_name='Rental Property Address'),
        ),
        migrations.AddField(
            model_name='landlord',
            name='property_city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='landlord',
            name='property_state',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='landlord',
            name='property_zip',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='landlord',
            name='routing_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='landlord',
            name='state',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='landlord',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='landlord',
            name='address',
            field=models.TextField(blank=True, verbose_name='Mailing Address'),
        ),
        migrations.AlterField(
            model_name='landlord',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='landlord',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Primary Phone'),
        ),
        migrations.AlterField(
            model_name='landlord',
            name='tax_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='Tax ID/SSN'),
        ),
    ]
