# Generated by Django 5.2.4 on 2025-07-03 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docsAppR', '0008_remove_landlord_name_landlord_account_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='claimReportDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='contractDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='dateOfLoss',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='endDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='startDate',
            field=models.DateTimeField(null=True),
        ),
    ]
