# Generated by Django 5.2.4 on 2025-07-03 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docsAppR', '0009_alter_client_claimreportdate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='landlord',
            old_name='account_number',
            new_name='company_city',
        ),
        migrations.RemoveField(
            model_name='landlord',
            name='account_name',
        ),
        migrations.RemoveField(
            model_name='landlord',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='landlord',
            name='routing_number',
        ),
        migrations.RemoveField(
            model_name='landlord',
            name='tax_id',
        ),
        migrations.AddField(
            model_name='landlord',
            name='broker_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Broker Email Address'),
        ),
        migrations.AddField(
            model_name='landlord',
            name='broker_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Owner/Broker Name'),
        ),
        migrations.AddField(
            model_name='landlord',
            name='broker_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Broker Phone Number'),
        ),
        migrations.AddField(
            model_name='landlord',
            name='company_contact_person',
            field=models.CharField(blank=True, max_length=100, verbose_name='Company Contact Person'),
        ),
        migrations.AddField(
            model_name='landlord',
            name='company_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Company Email Address'),
        ),
        migrations.AddField(
            model_name='landlord',
            name='company_mailing_address',
            field=models.TextField(blank=True, verbose_name='Company Mailing Address'),
        ),
        migrations.AddField(
            model_name='landlord',
            name='company_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Company Phone Number'),
        ),
        migrations.AddField(
            model_name='landlord',
            name='company_state',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='landlord',
            name='company_zip',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='landlord',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Contact Email Address'),
        ),
        migrations.AddField(
            model_name='landlord',
            name='contact_person_1',
            field=models.CharField(blank=True, max_length=100, verbose_name='Primary Contact Person'),
        ),
        migrations.AddField(
            model_name='landlord',
            name='contact_person_2',
            field=models.CharField(blank=True, max_length=100, verbose_name='Secondary Contact Person'),
        ),
        migrations.AddField(
            model_name='landlord',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Contact Phone Number'),
        ),
        migrations.AddField(
            model_name='landlord',
            name='real_estate_company',
            field=models.CharField(blank=True, max_length=100, verbose_name='Real Estate Company Name'),
        ),
    ]
