# Generated by Django 5.2.4 on 2025-07-04 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docsAppR', '0010_rename_account_number_landlord_company_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landlord',
            name='default_parking_fee',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='landlord',
            name='default_parking_spaces',
            field=models.PositiveSmallIntegerField(default=2),
        ),
    ]
