# Generated by Django 5.2.4 on 2025-07-05 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docsAppR', '0011_landlord_default_parking_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landlord',
            name='term_end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='landlord',
            name='term_start_date',
            field=models.DateTimeField(null=True),
        ),
    ]
