# Generated by Django 5.2.4 on 2025-07-06 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docsAppR', '0012_landlord_term_end_date_landlord_term_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landlord',
            name='term_end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='landlord',
            name='term_start_date',
            field=models.DateField(null=True),
        ),
    ]
