# Generated by Django 4.2.16 on 2025-12-20 06:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('docsAppR', '0012_auto_20251220_0445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='last_modified_onedrive',
        ),
        migrations.RemoveField(
            model_name='room',
            name='last_synced_to_django',
        ),
        migrations.AlterField(
            model_name='client',
            name='dateOfLoss',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='lossOfUseALE',
            field=models.CharField(blank=True, help_text='Loss of Use/ALE - Yes/No', max_length=255),
        ),
        migrations.AlterField(
            model_name='worktype',
            name='work_type_id',
            field=models.IntegerField(choices=[(100, 'Work Type 100'), (200, 'Work Type 200'), (300, 'Work Type 300'), (400, 'Work Type 400'), (500, 'Work Type 500'), (800, 'Work Type 800'), (900, 'Work Type 900 - HMR'), (6100, 'DAY 1'), (6200, 'DAY 2'), (6300, 'DAY 3'), (6400, 'DAY 4')], db_index=True, unique=True),
        ),
    ]
