# Generated by Django 5.2.4 on 2025-07-12 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docsAppR', '0013_alter_landlord_term_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landlord',
            name='default_inspection_fee',
            field=models.DecimalField(decimal_places=2, default=300.0, max_digits=10, verbose_name='Inspection/Clean-up Fee'),
        ),
        migrations.AlterField(
            model_name='landlord',
            name='term_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Lease End Date'),
        ),
        migrations.AlterField(
            model_name='landlord',
            name='term_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Lease Start Date'),
        ),
    ]
