# Generated by Django 4.2.16 on 2026-01-13 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docsAppR', '0013_remove_room_last_modified_onedrive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landlord',
            name='lease_special_notes',
            field=models.TextField(blank=True, help_text='Special instructions or notes to be included at the end of the Property section', null=True, verbose_name='Special Lease Instructions/Notes'),
        ),
        migrations.AlterField(
            model_name='client',
            name='claimReportDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='contractDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='dateOfLoss',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
