# Generated by Django 5.2.4 on 2025-07-14 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docsAppR', '0014_landlord_default_inspection_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landlord',
            name='default_max_occupants',
            field=models.PositiveSmallIntegerField(default=10),
        ),
    ]
