# Generated by Django 4.2.16 on 2026-01-21 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('docsAppR', '0014_landlord_lease_special_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaseDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('engagement_agreement', 'Engagement Agreement'), ('term_sheet', 'Term Sheet'), ('month_to_month_rental', 'Month to Month Rental'), ('input_sheet', 'Input Sheet'), ('invoice', 'Invoice'), ('package', 'Complete Package')], max_length=50)),
                ('document_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(blank=True, help_text='Path to generated PDF on server', max_length=500)),
                ('lessor_name', models.CharField(blank=True, max_length=255)),
                ('property_address', models.CharField(blank=True, max_length=500)),
                ('monthly_rent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('lease_start_date', models.DateField(blank=True, null=True)),
                ('lease_end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generated', 'Generated'), ('sent_for_signature', 'Sent for Signature'), ('signed', 'Signed'), ('invoice_created', 'Invoice Created'), ('package_sent', 'Package Sent to Insurance'), ('payment_pending', 'Payment Pending'), ('payment_received', 'Payment Received'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=30)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('sent_for_signature_at', models.DateTimeField(blank=True, null=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('invoice_created_at', models.DateTimeField(blank=True, null=True)),
                ('package_sent_at', models.DateTimeField(blank=True, null=True)),
                ('payment_received_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_renewal', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lease_documents', to='docsAppR.client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_lease_documents', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_lease_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeasePackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('package_name', models.CharField(max_length=255)),
                ('overall_status', models.CharField(choices=[('draft', 'Draft'), ('generated', 'Generated'), ('sent_for_signature', 'Sent for Signature'), ('signed', 'Signed'), ('invoice_created', 'Invoice Created'), ('package_sent', 'Package Sent to Insurance'), ('payment_pending', 'Payment Pending'), ('payment_received', 'Payment Received'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=30)),
                ('total_monthly_rent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lease_packages', to='docsAppR.client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('documents', models.ManyToManyField(related_name='packages', to='docsAppR.leasedocument')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeaseActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('created', 'Document Created'), ('generated', 'PDF Generated'), ('downloaded', 'Downloaded'), ('status_changed', 'Status Changed'), ('sent_email', 'Email Sent'), ('viewed', 'Viewed'), ('note_added', 'Note Added')], max_length=30)),
                ('description', models.TextField()),
                ('old_status', models.CharField(blank=True, max_length=30)),
                ('new_status', models.CharField(blank=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lease_activities', to='docsAppR.client')),
                ('lease_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='docsAppR.leasedocument')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Lease Activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='leasedocument',
            index=models.Index(fields=['client', 'status'], name='docsAppR_le_client__358a6d_idx'),
        ),
        migrations.AddIndex(
            model_name='leasedocument',
            index=models.Index(fields=['status'], name='docsAppR_le_status_1038d3_idx'),
        ),
        migrations.AddIndex(
            model_name='leasedocument',
            index=models.Index(fields=['-created_at'], name='docsAppR_le_created_7a64cb_idx'),
        ),
        migrations.AddIndex(
            model_name='leasedocument',
            index=models.Index(fields=['created_by'], name='docsAppR_le_created_2ef81b_idx'),
        ),
        migrations.AddIndex(
            model_name='leaseactivity',
            index=models.Index(fields=['-created_at'], name='docsAppR_le_created_40bb6f_idx'),
        ),
        migrations.AddIndex(
            model_name='leaseactivity',
            index=models.Index(fields=['client', '-created_at'], name='docsAppR_le_client__e1a2d6_idx'),
        ),
        migrations.AddIndex(
            model_name='leaseactivity',
            index=models.Index(fields=['performed_by', '-created_at'], name='docsAppR_le_perform_1e9912_idx'),
        ),
    ]
