# Generated by Django 4.2.16 on 2026-01-22 02:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('docsAppR', '0015_leasedocument_leasepackage_leaseactivity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lessor_name', models.CharField(max_length=255, verbose_name='Lessor Full Name')),
                ('lessor_address', models.CharField(blank=True, max_length=500)),
                ('lessor_city', models.CharField(blank=True, max_length=100)),
                ('lessor_state', models.CharField(blank=True, max_length=50)),
                ('lessor_zip', models.CharField(blank=True, max_length=20)),
                ('lessor_phone', models.CharField(blank=True, max_length=50)),
                ('lessor_email', models.EmailField(blank=True, max_length=254)),
                ('lessor_contact_person_1', models.CharField(blank=True, max_length=255)),
                ('lessor_contact_person_2', models.CharField(blank=True, max_length=255)),
                ('lessor_contact_phone', models.CharField(blank=True, max_length=50)),
                ('lessor_contact_email', models.EmailField(blank=True, max_length=254)),
                ('property_address', models.CharField(max_length=500)),
                ('property_city', models.CharField(blank=True, max_length=100)),
                ('property_state', models.CharField(blank=True, max_length=50)),
                ('property_zip', models.CharField(blank=True, max_length=20)),
                ('bedrooms', models.PositiveIntegerField(default=1)),
                ('lease_start_date', models.DateField()),
                ('lease_end_date', models.DateField()),
                ('lease_agreement_date', models.DateField(blank=True, null=True)),
                ('rental_months', models.PositiveIntegerField(default=12)),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('security_deposit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rent_due_day', models.PositiveIntegerField(default=1)),
                ('late_fee', models.DecimalField(decimal_places=2, default=50, max_digits=10)),
                ('late_fee_start_day', models.PositiveIntegerField(default=5)),
                ('eviction_day', models.PositiveIntegerField(default=10)),
                ('nsf_fee', models.DecimalField(decimal_places=2, default=35, max_digits=10)),
                ('max_occupants', models.PositiveIntegerField(default=10)),
                ('parking_spaces', models.PositiveIntegerField(default=2)),
                ('parking_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('inspection_fee', models.DecimalField(decimal_places=2, default=300, max_digits=10)),
                ('real_estate_company', models.CharField(blank=True, max_length=255)),
                ('company_mailing_address', models.CharField(blank=True, max_length=500)),
                ('company_city', models.CharField(blank=True, max_length=100)),
                ('company_state', models.CharField(blank=True, max_length=50)),
                ('company_zip', models.CharField(blank=True, max_length=20)),
                ('company_contact_person', models.CharField(blank=True, max_length=255)),
                ('company_phone', models.CharField(blank=True, max_length=50)),
                ('company_email', models.EmailField(blank=True, max_length=254)),
                ('broker_name', models.CharField(blank=True, max_length=255)),
                ('broker_phone', models.CharField(blank=True, max_length=50)),
                ('broker_email', models.EmailField(blank=True, max_length=254)),
                ('special_notes', models.TextField(blank=True)),
                ('is_renewal', models.BooleanField(default=False)),
                ('exclude_security_deposit', models.BooleanField(default=False)),
                ('exclude_inspection_fee', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generated', 'Generated'), ('sent_for_signature', 'Sent for Signature'), ('signed', 'Signed'), ('invoice_created', 'Invoice Created'), ('package_sent', 'Package Sent to Insurance'), ('payment_pending', 'Payment Pending'), ('payment_received', 'Payment Received'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=30)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('sent_for_signature_at', models.DateTimeField(blank=True, null=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('invoice_created_at', models.DateTimeField(blank=True, null=True)),
                ('package_sent_at', models.DateTimeField(blank=True, null=True)),
                ('payment_received_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='leasepackage',
            name='client',
        ),
        migrations.RemoveField(
            model_name='leasepackage',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='leasepackage',
            name='documents',
        ),
        migrations.AlterModelOptions(
            name='leasedocument',
            options={'ordering': ['document_type']},
        ),
        migrations.RemoveIndex(
            model_name='leaseactivity',
            name='docsAppR_le_client__e1a2d6_idx',
        ),
        migrations.RemoveIndex(
            model_name='leaseactivity',
            name='docsAppR_le_perform_1e9912_idx',
        ),
        migrations.RemoveIndex(
            model_name='leasedocument',
            name='docsAppR_le_client__358a6d_idx',
        ),
        migrations.RemoveIndex(
            model_name='leasedocument',
            name='docsAppR_le_status_1038d3_idx',
        ),
        migrations.RemoveIndex(
            model_name='leasedocument',
            name='docsAppR_le_created_7a64cb_idx',
        ),
        migrations.RemoveIndex(
            model_name='leasedocument',
            name='docsAppR_le_created_2ef81b_idx',
        ),
        migrations.RemoveField(
            model_name='leaseactivity',
            name='client',
        ),
        migrations.RemoveField(
            model_name='leaseactivity',
            name='lease_document',
        ),
        migrations.RemoveField(
            model_name='leasedocument',
            name='client',
        ),
        migrations.RemoveField(
            model_name='leasedocument',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='leasedocument',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='leasedocument',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='leasedocument',
            name='invoice_created_at',
        ),
        migrations.RemoveField(
            model_name='leasedocument',
            name='is_renewal',
        ),
        migrations.RemoveField(
            model_name='leasedocument',
            name='last_modified_by',
        ),
        migrations.RemoveField(
            model_name='leasedocument',
            name='lease_end_date',
        ),
        migrations.RemoveField(
            model_name='leasedocument',
            name='lease_start_date',
        ),
        migrations.RemoveField(
            model_name='leasedocument',
            name='lessor_name',
        ),
        migrations.RemoveField(
            model_name='leasedocument',
            name='monthly_rent',
        ),
        migrations.RemoveField(
            model_name='leasedocument',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='leasedocument',
            name='package_sent_at',
        ),
        migrations.RemoveField(
            model_name='leasedocument',
            name='payment_received_at',
        ),
        migrations.RemoveField(
            model_name='leasedocument',
            name='property_address',
        ),
        migrations.RemoveField(
            model_name='leasedocument',
            name='sent_for_signature_at',
        ),
        migrations.RemoveField(
            model_name='leasedocument',
            name='signed_at',
        ),
        migrations.RemoveField(
            model_name='leasedocument',
            name='status',
        ),
        migrations.RemoveField(
            model_name='leasedocument',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='leaseactivity',
            name='activity_type',
            field=models.CharField(choices=[('created', 'Lease Created'), ('generated', 'Documents Generated'), ('document_created', 'Document Created'), ('downloaded', 'Downloaded'), ('status_changed', 'Status Changed'), ('sent_email', 'Email Sent'), ('viewed', 'Viewed'), ('note_added', 'Note Added')], max_length=30),
        ),
        migrations.AlterField(
            model_name='leasedocument',
            name='document_type',
            field=models.CharField(choices=[('engagement_agreement', 'Engagement Agreement'), ('term_sheet', 'Term Sheet'), ('month_to_month_rental', 'Month to Month Rental'), ('input_sheet', 'Input Sheet'), ('invoice', 'Invoice')], max_length=50),
        ),
        migrations.AlterField(
            model_name='leasedocument',
            name='generated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddIndex(
            model_name='leaseactivity',
            index=models.Index(fields=['lease', '-created_at'], name='docsAppR_le_lease_i_5e649b_idx'),
        ),
        migrations.DeleteModel(
            name='LeasePackage',
        ),
        migrations.AddField(
            model_name='lease',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='docsAppR.client'),
        ),
        migrations.AddField(
            model_name='lease',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_leases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lease',
            name='last_modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_leases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaseactivity',
            name='lease',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='docsAppR.lease'),
        ),
        migrations.AddField(
            model_name='leasedocument',
            name='lease',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='docsAppR.lease'),
        ),
        migrations.AddIndex(
            model_name='lease',
            index=models.Index(fields=['client', 'status'], name='docsAppR_le_client__9aff03_idx'),
        ),
        migrations.AddIndex(
            model_name='lease',
            index=models.Index(fields=['status'], name='docsAppR_le_status_c6e3f4_idx'),
        ),
        migrations.AddIndex(
            model_name='lease',
            index=models.Index(fields=['-created_at'], name='docsAppR_le_created_c632fc_idx'),
        ),
        migrations.AddIndex(
            model_name='lease',
            index=models.Index(fields=['lease_start_date', 'lease_end_date'], name='docsAppR_le_lease_s_fe3ed0_idx'),
        ),
    ]
