# Generated by Django 5.2.4 on 2025-07-14 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docsAppR', '0015_alter_landlord_default_max_occupants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landlord',
            name='broker_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Broker Email Address'),
        ),
        migrations.AlterField(
            model_name='landlord',
            name='company_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Company Email Address'),
        ),
        migrations.AlterField(
            model_name='landlord',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Contact Email Address'),
        ),
        migrations.AlterField(
            model_name='landlord',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address'),
        ),
    ]
