# Generated by Django 4.2.16 on 2026-01-29 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docsAppR', '0018_make_lease_dates_nullable'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailParsingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Rule name for identification', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('subject_keywords', models.CharField(help_text="Comma-separated keywords to match in subject (e.g., 'signed, executed')", max_length=255)),
                ('target_status', models.CharField(choices=[('draft', 'Draft'), ('generated', 'Generated'), ('review', 'Under Review'), ('sent_for_signature', 'Sent for Signature'), ('signed', 'Signed'), ('invoice_created', 'Invoice Created'), ('package_sent', 'Package Sent to Insurance'), ('payment_pending', 'Payment Pending'), ('payment_received', 'Payment Received'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], help_text='Status to set when this rule matches', max_length=30)),
                ('claim_identifier_pattern', models.CharField(default='CLAIM[#:\\s]*(\\w+)', help_text='Regex pattern to extract claim number from email', max_length=255)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email Parsing Rule',
                'verbose_name_plural': 'Email Parsing Rules',
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.AddField(
            model_name='lease',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lease',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('generated', 'Generated'), ('review', 'Under Review'), ('sent_for_signature', 'Sent for Signature'), ('signed', 'Signed'), ('invoice_created', 'Invoice Created'), ('package_sent', 'Package Sent to Insurance'), ('payment_pending', 'Payment Pending'), ('payment_received', 'Payment Received'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=30),
        ),
        migrations.AlterField(
            model_name='leaseactivity',
            name='activity_type',
            field=models.CharField(choices=[('draft', 'Draft Created'), ('generated', 'Documents Generated'), ('review', 'Documents Reviewed'), ('sent_for_signature', 'Sent for Signature'), ('signed', 'Lease Signed'), ('invoice_created', 'Invoice Created'), ('package_sent', 'Package Sent'), ('payment_pending', 'Payment Pending'), ('payment_received', 'Payment Received'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('note_added', 'Note Added'), ('document_downloaded', 'Document Downloaded'), ('document_viewed', 'Document Viewed'), ('email_parsed', 'Email Auto-Processed')], max_length=30),
        ),
        migrations.AlterField(
            model_name='roomworktypevalue',
            name='value_type',
            field=models.CharField(blank=True, choices=[('', 'No Value'), ('TBD', 'To Be Determined'), ('NA', 'Not Applicable'), ('LOS', 'Line Of Sight'), ('TRAVEL', 'Travel Area')], default='', max_length=10),
        ),
        migrations.CreateModel(
            name='PipelineStageAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('draft', 'Draft'), ('generated', 'Generated'), ('review', 'Review'), ('sent_for_signature', 'Sent for Signature'), ('signed', 'Signed'), ('invoice_created', 'Invoice Created'), ('package_sent', 'Package Sent'), ('payment_pending', 'Payment Pending'), ('payment_received', 'Payment Received'), ('completed', 'Completed')], max_length=30, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of what happens at this stage')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order in pipeline')),
                ('assigned_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_pipeline_stages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pipeline Stage Assignment',
                'verbose_name_plural': 'Pipeline Stage Assignments',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ParsedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.CharField(help_text='Email message ID', max_length=255, unique=True)),
                ('sender', models.EmailField(max_length=254)),
                ('subject', models.TextField()),
                ('body_preview', models.TextField(blank=True, max_length=500)),
                ('received_at', models.DateTimeField()),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('success', 'Successfully Processed'), ('no_match', 'No Rule Matched'), ('no_lease', 'Lease Not Found'), ('error', 'Error Processing')], max_length=20)),
                ('old_status', models.CharField(blank=True, max_length=30)),
                ('new_status', models.CharField(blank=True, max_length=30)),
                ('error_message', models.TextField(blank=True)),
                ('lease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parsed_emails', to='docsAppR.lease')),
                ('matched_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_emails', to='docsAppR.emailparsingrule')),
            ],
            options={
                'verbose_name': 'Parsed Email',
                'verbose_name_plural': 'Parsed Emails',
                'ordering': ['-processed_at'],
            },
        ),
        migrations.CreateModel(
            name='LeaseStageCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('draft', 'Draft'), ('generated', 'Generated'), ('review', 'Review'), ('sent_for_signature', 'Sent for Signature'), ('signed', 'Signed'), ('invoice_created', 'Invoice Created'), ('package_sent', 'Package Sent'), ('payment_pending', 'Payment Pending'), ('payment_received', 'Payment Received'), ('completed', 'Completed')], max_length=30)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('assigned_user', models.ForeignKey(blank=True, help_text='User assigned to complete this stage', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_lease_stages', to=settings.AUTH_USER_MODEL)),
                ('completed_by', models.ForeignKey(blank=True, help_text='User who actually completed this stage', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_lease_stages', to=settings.AUTH_USER_MODEL)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_completions', to='docsAppR.lease')),
            ],
            options={
                'verbose_name': 'Lease Stage Completion',
                'verbose_name_plural': 'Lease Stage Completions',
                'ordering': ['lease', 'stage'],
                'unique_together': {('lease', 'stage')},
            },
        ),
    ]
