# Generated by Django 4.2.16 on 2026-02-03 00:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('docsAppR', '0019_emailparsingrule_lease_reviewed_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomScopeChecklist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('clg_material', models.CharField(blank=True, max_length=20)),
                ('clg_construction', models.CharField(blank=True, max_length=20)),
                ('clg_finish', models.CharField(blank=True, max_length=20)),
                ('clg_activity', models.CharField(blank=True, max_length=20)),
                ('clg_sf', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('lit_type', models.CharField(blank=True, max_length=20)),
                ('lit_activity', models.CharField(blank=True, max_length=20)),
                ('lit_qty', models.IntegerField(blank=True, null=True)),
                ('hvc_type', models.CharField(blank=True, max_length=20)),
                ('hvc_activity', models.CharField(blank=True, max_length=20)),
                ('hvc_qty', models.IntegerField(blank=True, null=True)),
                ('wal_material', models.CharField(blank=True, max_length=20)),
                ('wal_finish', models.CharField(blank=True, max_length=20)),
                ('wal_activity', models.CharField(blank=True, max_length=20)),
                ('wal_sf', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ele_outlets', models.IntegerField(blank=True, null=True)),
                ('ele_switches', models.IntegerField(blank=True, null=True)),
                ('ele_sw3', models.IntegerField(blank=True, null=True)),
                ('ele_activity', models.CharField(blank=True, max_length=20)),
                ('flr_type', models.CharField(blank=True, max_length=20)),
                ('flr_activity', models.CharField(blank=True, max_length=20)),
                ('flr_sf', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bb_height', models.CharField(blank=True, max_length=20)),
                ('bb_activity', models.CharField(blank=True, max_length=20)),
                ('bb_lf', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('trim_type', models.CharField(blank=True, max_length=20)),
                ('trim_crown', models.CharField(blank=True, max_length=10)),
                ('trim_chairrail', models.CharField(blank=True, max_length=10)),
                ('trim_activity', models.CharField(blank=True, max_length=20)),
                ('dor_type', models.CharField(blank=True, max_length=20)),
                ('dor_activity', models.CharField(blank=True, max_length=20)),
                ('dor_qty', models.IntegerField(blank=True, null=True)),
                ('open_activity', models.CharField(blank=True, max_length=20)),
                ('open_qty', models.IntegerField(blank=True, null=True)),
                ('wdw_type', models.CharField(blank=True, max_length=20)),
                ('wdw_covers', models.CharField(blank=True, max_length=20)),
                ('wdw_activity', models.CharField(blank=True, max_length=20)),
                ('wdw_qty', models.IntegerField(blank=True, null=True)),
                ('closet_type', models.CharField(blank=True, max_length=20)),
                ('closet_rod', models.CharField(blank=True, max_length=10)),
                ('closet_lf', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ins_type', models.CharField(blank=True, max_length=20)),
                ('ins_rvalue', models.CharField(blank=True, max_length=20)),
                ('ins_sf', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('frm_type', models.CharField(blank=True, max_length=20)),
                ('frm_activity', models.CharField(blank=True, max_length=20)),
                ('frm_lf', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('activity_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scope_checklists', to='docsAppR.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_scope_checklists', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scope_checklists', to='docsAppR.room')),
            ],
            options={
                'ordering': ['client', 'room'],
                'indexes': [models.Index(fields=['client'], name='docsAppR_ro_client__76dec7_idx'), models.Index(fields=['room'], name='docsAppR_ro_room_id_fe19b6_idx')],
                'unique_together': {('room', 'client')},
            },
        ),
    ]
