# Generated by Django 4.2.16 on 2026-02-18 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docsAppR', '0020_roomscopechecklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='encircle_claim_id',
            field=models.CharField(blank=True, help_text='Encircle property claim ID (set after push to Encircle)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='encircle_synced_at',
            field=models.DateTimeField(blank=True, help_text='Last time this claim was pushed to Encircle', null=True),
        ),
    ]
