"""
Django settings for mitigation_app project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from django.core.management.utils import get_random_secret_key
import sys
import dj_database_url
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", get_random_secret_key())

# SECURITY WARNING: don't run with debug turned on in production!
#DEBUG = os.getenv("DEBUG", "False") == "False"
DEBUG=True
ALLOWED_HOSTS = os.getenv("DJANGO_ALLOWED_HOSTS", "127.0.0.1,localhost,claimetapp.com,www.claimetapp.com").split(",")

CSRF_TRUSTED_ORIGINS = [
    "https://sea-lion-app-o5y45.ondigitalocean.app",
    "https://claimetapp.com",
    "https://www.claimetapp.com",
]


#DEVELOPMENT_MODE = os.getenv("DEVELOPMENT_MODE", "False") == "True"
DEVELOPMENT_MODE = True
# Application definition



INSTALLED_APPS = [
    # Core app (models, migrations, shared logic)
    'docsAppR',

    # Feature apps
    'dashboard',
    'claims',
    'scope_checklist',
    'lease_manager',
    'email_manager',
    'labels',
    'readings',
    'sensor_renamer',
    'equipment_checker',
    'claim_images',
    'encircle',
    'box_calculator',
    'cps_report',
    'contractor_hub',
    'dev_hub',
    'tasks',

    # Auth
    #'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',

    # Django built-ins
    'django.contrib.humanize',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Celery & Background Tasks
    'django_celery_beat',
    'django_celery_results',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'mitigation_app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'builtins': [  # Add this key
                'django.templatetags.l10n',  # Required for date formatting
            ],
        },
    },
]

WSGI_APPLICATION = 'mitigation_app.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

if DEVELOPMENT_MODE is True:
        DATABASES = {
            "default" : {
                "ENGINE" : "django.db.backends.sqlite3",
                "NAME" : os.path.join(BASE_DIR, "db.sqlite3"),
            }
        }
elif len(sys.argv) > 0 and sys.argv[1] != 'collectstatic':
    if os.getenv("DATABASE_URL", None) is None:
        raise Exception("DATABASE_URL environment variable not defined")
    DATABASE = {
        "default": dj_database_url.parse(os.environ.get("DATABASE_URL")),
    }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Django Allauth settings
SITE_ID = 1  # Required for allauth
LOGIN_REDIRECT_URL = '/'  # Where to redirect after successful login
ACCOUNT_EMAIL_REQUIRED = True                    # Email is required at signup
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'         # Must verify before first login
ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS = 3       # Verification link lives 3 days
ACCOUNT_ADAPTER = 'docsAppR.adapters.AccountAdapter'  # Custom: resend on unverified re-signup
#settings.ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']

AUTH_PASSWORD_VALIDATORS = [{'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'}, {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'}, {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'}, {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'}]
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # For production
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),  # Your static files directory
]

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ==================== Email Configuration ====================
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)

# ── Lease / signature emails — optional dedicated sender (e.g. Outlook) ──────
# Signature- and lease-related emails (signing invites, OTP codes, document
# packages, and signing notifications) send from THIS account instead of the
# default mailbox above, so they come from the firm's ALE/lease address.
# Set these in the environment (.env). When LEASE_EMAIL_HOST_USER /
# LEASE_EMAIL_HOST_PASSWORD are blank, those emails fall back to the default
# connection automatically — so nothing breaks until you configure it.
#   Outlook / Microsoft 365 business : smtp.office365.com    port 587  TLS
#   Outlook.com (personal)           : smtp-mail.outlook.com port 587  TLS
LEASE_EMAIL_HOST          = os.getenv('LEASE_EMAIL_HOST', 'smtp.office365.com')
LEASE_EMAIL_PORT          = int(os.getenv('LEASE_EMAIL_PORT', '587'))
LEASE_EMAIL_USE_TLS       = os.getenv('LEASE_EMAIL_USE_TLS', 'True') == 'True'
LEASE_EMAIL_HOST_USER     = os.getenv('LEASE_EMAIL_HOST_USER', '')
LEASE_EMAIL_HOST_PASSWORD = os.getenv('LEASE_EMAIL_HOST_PASSWORD', '')
# From-address shown to recipients; defaults to the lease mailbox login.
LEASE_FROM_EMAIL          = os.getenv('LEASE_FROM_EMAIL', '') or LEASE_EMAIL_HOST_USER

AUTH_USER_MODEL = 'docsAppR.CustomUser'

# Add these settings for media files
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# ==================== Anthropic / Claude API ====================
ANTHROPIC_API_KEY = os.getenv('ANTHROPIC_API_KEY', '')

# ==================== OneDrive Configuration ====================
ONEDRIVE_CLIENT_ID = os.getenv('ONEDRIVE_CLIENT_ID', '')
ONEDRIVE_CLIENT_SECRET = os.getenv('ONEDRIVE_CLIENT_SECRET', '')  # Optional for native client
ONEDRIVE_REDIRECT_URI = os.getenv(
    'ONEDRIVE_REDIRECT_URI',
    'http://localhost:8000/auth/onedrive/callback/'
)
ONEDRIVE_USE_SHARED_DRIVE = os.getenv('ONEDRIVE_USE_SHARED_DRIVE', 'True') == 'True'

# Existing refresh token (for native client authentication)
ONEDRIVE_REFRESH_TOKEN = os.getenv('ONEDRIVE_REFRESH_TOKEN', '')

# Token encryption key (generate with: python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())")
TOKEN_ENCRYPTION_KEY = os.getenv('TOKEN_ENCRYPTION_KEY', '')

# Webhook configuration
ONEDRIVE_WEBHOOK_SECRET = os.getenv('ONEDRIVE_WEBHOOK_SECRET', 'generate-random-secret')
ONEDRIVE_WEBHOOK_URL = os.getenv(
    'ONEDRIVE_WEBHOOK_URL',
    'https://yourdomain.com/webhooks/onedrive/'
)

# ==================== Celery Configuration ====================
CELERY_BROKER_URL = os.getenv('REDIS_URL', 'redis://redis:6379/0')
CELERY_RESULT_BACKEND = 'django-db'
CELERY_CACHE_BACKEND = 'django-cache'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'America/New_York'  # Adjust to your timezone
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

# Celery Beat Schedule
from celery.schedules import crontab

# ── Dev Hub notification email ────────────────────────────────────────────
NOTIFY_EMAIL = os.getenv('NOTIFY_EMAIL', 'wsbjoe9@gmail.com')

# ── AI cost management ─────────────────────────────────────────────────────
# Monthly spend threshold in USD — alert email goes to NOTIFY_EMAIL when crossed
AI_MONTHLY_BUDGET_USD   = float(os.getenv('AI_MONTHLY_BUDGET_USD', '50.0'))
# Fraction of budget that triggers a low-balance warning (0.8 = 80%)
AI_LOW_BALANCE_THRESHOLD = float(os.getenv('AI_LOW_BALANCE_THRESHOLD', '0.80'))

CELERY_BEAT_SCHEDULE = {
    'renew-onedrive-subscriptions': {
        'task': 'docsAppR.tasks.renew_subscriptions_task',
        'schedule': crontab(minute='*/15'),
    },
    'check-delta-sync': {
        'task': 'docsAppR.tasks.check_all_folders_for_changes',
        'schedule': crontab(minute='*/5'),
    },
    # ── Email scheduling (was completely missing — root cause of scheduling bug)
    'process-scheduled-emails': {
        'task': 'email_manager.tasks.send_scheduled_emails_task',
        'schedule': crontab(minute='*'),  # poll every minute
    },
    # ── Dev Hub: weekly progress report — Monday 8 AM
    'dev-hub-weekly-report': {
        'task': 'dev_hub.tasks.send_weekly_progress_report',
        'schedule': crontab(hour=8, minute=0, day_of_week=1),
    },
    # ── AI: weekly cost report — Monday 8:05 AM (5 min after progress report)
    'ai-weekly-cost-report': {
        'task': 'dev_hub.tasks.send_weekly_ai_cost_report',
        'schedule': crontab(hour=8, minute=5, day_of_week=1),
    },
    # ── AI: low-balance check — every hour
    'ai-budget-alert-check': {
        'task': 'dev_hub.tasks.check_ai_budget_alert',
        'schedule': crontab(minute=0),  # top of every hour
    },
    # ── Encircle → Claimet daily inbound sync — every day at 6:00 AM ET
    'encircle-daily-sync': {
        'task': 'docsAppR.tasks.sync_encircle_claims_task',
        'schedule': crontab(hour=6, minute=0),
        'kwargs': {'triggered_by': 'schedule'},
    },
}

# ==================== Cache Configuration ====================
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': os.getenv('REDIS_URL', 'redis://redis:6379/1'),
        'KEY_PREFIX': 'mitigation',
        'TIMEOUT': 3600,  # 1 hour default
    }
}

# ==================== File Upload Settings ====================
DATA_UPLOAD_MAX_MEMORY_SIZE = 104857600  # 100MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 104857600

# ==================== Logging Configuration ====================
# Create logs directory
os.makedirs(os.path.join(BASE_DIR, 'logs'), exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'onedrive_sync.log'),
            'maxBytes': 10485760,  # 10MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        # Catch-all: any logger without an explicit entry below (including
        # third-party libs) emits at INFO to file + console. Without this,
        # records propagating to the root were dropped by Python's WARNING-level
        # "last resort" handler, so INFO logs vanished in the web process.
        'handlers': ['file', 'console'],
        'level': 'INFO',
    },
    'loggers': {
        'onedrive_sync': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        'celery': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        # The application package. claims_views, tasks, encircle_sync, etc. all
        # log under "docsAppR.*" via logging.getLogger(__name__). These were
        # never configured, so every claim-creation and Encircle-push log line
        # was silently discarded in the web process. Emit them explicitly.
        'docsAppR': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        # Surface Django request/server errors too (e.g. 500s in views).
        'django': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

